# 1. What is a Python library? Why ^o we use Python libraries?

A Python library is a collection of modules and functions that enable you to perform specific tasks without having to write the code from scratch. Libraries in Python are pre-written pieces of code that provide reusable functionality to help developers accomplish common tasks efficiently. These libraries cover a wide range of domains and can be related to various purposes, such as data manipulation, scientific computing, web development, machine learning, and more.

Here are some reasons why Python libraries are widely used:

Code Reusability: Libraries contain pre-written code that you can reuse in your own projects. This helps save time and effort, as you don't need to reinvent the wheel for common tasks.

Efficiency: Libraries are often optimized and well-tested, providing efficient solutions to common problems. This allows developers to focus on high-level aspects of their projects without getting bogged down in low-level implementation details.

Community Contributions: The Python community is large and active, leading to a vast ecosystem of libraries. This means that if you have a specific task, there's a good chance that a library already exists to handle it.

Specialized Functionality: Many libraries are designed to address specific domains or industries, providing specialized functionality and tools. For example, NumPy is widely used in scientific computing, while Django is popular for web development.

Open Source Collaboration: Python libraries are often open source, encouraging collaboration and contributions from the community. This fosters the development of high-quality, well-maintained code.

Interoperability: Python libraries are designed to work seamlessly with each other, promoting interoperability and the ability to combine different tools to create powerful solutions.

Overall, Python libraries enhance the productivity of developers by offering a rich set of tools and functionality that can be easily integrated into their projects, enabling them to focus on solving specific problems rather than writing generic code.

# 2. What is the ^ifference between Numpy array an^ List?
NumPy arrays and Python lists are both used to store and manipulate collections of data, but there are several key differences between them:

Homogeneity:

NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and operations on the data.
List: Python lists can contain elements of different data types, making them heterogeneous.
Performance:

NumPy Array: NumPy arrays are more memory-efficient and offer faster numerical operations compared to Python lists. NumPy is implemented in C and operates on contiguous blocks of memory, leading to better performance for mathematical operations.
List: Python lists are more flexible but can be less efficient for numerical operations, especially when dealing with large datasets.
Functionality:

NumPy Array: NumPy provides a wide range of mathematical functions and operations that can be applied to entire arrays without the need for explicit looping. This makes it well-suited for numerical and scientific computing.
List: Lists are more general-purpose and offer a variety of methods for basic operations. However, numerical operations on lists often require explicit iteration.
Size:

NumPy Array: NumPy arrays are more compact in terms of memory usage compared to Python lists, especially when dealing with large datasets.
List: Lists may consume more memory due to their flexibility in handling different data types.
Syntax:

NumPy Array: NumPy arrays support vectorized operations, allowing you to perform operations on entire arrays at once. This leads to concise and readable code.
List: Performing operations on each element of a list usually involves using loops, which can make the code longer and potentially less efficient for numerical operations.
In summary, while lists provide more flexibility and are suitable for a wide range of tasks, NumPy arrays are specifically designed for numerical operations and offer better performance and memory efficiency in such scenarios. The choice between them depends on the specific requirements of the task at hand.

In [7]:
#3. Find the shape, size and dimension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr.shape

(3, 4)

In [9]:
arr.size

12

In [11]:
arr.ndim

2

In [12]:
# 4. Write python code to access the first row of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr[0]

array([1, 2, 3, 4])

In [19]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

arr[2,3]

12

In [20]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

arr[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [26]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

import random
np.random.random((3,3))

array([[0.19693362, 0.96166016, 0.51083459],
       [0.72746312, 0.21584832, 0.12195733],
       [0.77787646, 0.20520065, 0.94100446]])

#8. Describe the difference between np.random.rand and np.random.randn?

It seems there's a typo in your question, but I'll assume you meant to ask about the difference between np.random.rand and np.random.randn in the NumPy library.

np.random.rand:

This function generates random values from a uniform distribution over the interval [0, 1) .
It takes dimensions as arguments and returns an array with random values in the specified shape.
Syntax: np.random.rand(d0, d1, ..., dn)
Example:

In [31]:
import numpy as np

random_values = np.random.rand(3, 3)
random_values


array([[0.71624202, 0.95140191, 0.58580024],
       [0.45940741, 0.60927947, 0.48205087],
       [0.34301042, 0.41572508, 0.50999001]])

np.random.randn:

This function generates random values from a standard normal distribution (mean=0, standard deviation=1).
Like np.random.rand, it takes dimensions as arguments and returns an array with random values in the specified shape.
Syntax: np.random.randn(d0, d1, ..., dn)
Example:




In [34]:

import numpy as np

random_values = np.random.randn(3, 3)
random_values

array([[ 0.55425148,  1.5019002 ,  1.63773333],
       [ 1.35583024, -0.52141341,  2.18476938],
       [-2.2127371 ,  0.83093258,  0.31142297]])

In [43]:
#9. Write co^e to increase the ^imension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
arr.ndim
arr2=np.expand_dims(arr,axis=0)

In [44]:
arr.ndim

2

In [41]:
arr2.ndim

3

In [45]:
#10. How to transpose the following array in NumPy?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [59]:
#11. Consi^er the following matrix:
#Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

A=np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B=np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [60]:
A

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [61]:
B

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [62]:
#1.Index wise multiplication'

C=np.multiply(A,B)

In [63]:
C

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])

In [67]:
#2. Matrix multiplication'
A=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
A * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [69]:
# Add both matrices
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [70]:
# subtract matrix B from A
B - A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [71]:
# Divide matrix B by A
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
arr.byteswap()

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

# 13. What is the significance of the np.linalg.inv function?
The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. In other words, it calculates the inverse of a square matrix, if it exists. The resulting inverse matrix, when multiplied by the original matrix, yields the identity matrix.

Here's an example of how to use np.linalg.inv:

python
Copy code

The significance of np.linalg.inv lies in various applications, such as:

Solving Linear Systems: Given a system of linear equations in the form Ax = B, where A is a coefficient matrix and B is a column vector, the solution x can be found using the inverse of A: x = A^(-1) * B.

Matrix Equation Solving: It is used to solve matrix equations of the form AX = B, where A, B, and X are matrices. The solution is given by X = A^(-1) * B.

Determining Singular Matrices: If the matrix is singular (non-invertible), attempting to compute its inverse will result in an error. Therefore, the presence or absence of an inverse provides information about the singularity of a matrix.

It's important to note that not all matrices have an inverse. A matrix must be square (having the same number of rows and columns) and non-singular (having a non-zero determinant) to have an inverse. The np.linalg.inv function is a valuable tool for solving various mathematical problems and linear algebra applications.

In [75]:
import numpy as np

# Create a square matrix
matrix = np.array([[4, 7],
                   [2, 6]])

# Calculate the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

# Print the result
print("Original Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [76]:
#14. What does the np.reshape function do, and how is it used?

import numpy as np

# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 array
reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


#15. What is broadcasting in Numpy?
Broadcasting in NumPy is a mechanism that allows NumPy to perform operations on arrays of different shapes and sizes. It enables element-wise operations between arrays of different shapes without explicitly reshaping them. Broadcasting is particularly useful when working with arrays of different dimensions or when performing operations between arrays and scalars.

The key concept behind broadcasting is that when operating on two arrays, NumPy compares their shapes element-wise, starting from the trailing dimensions. The dimensions are compatible for broadcasting when either:

They are equal.
One of them is 1.
NumPy automatically adjusts the smaller array to have the same shape as the larger one, effectively replicating the smaller array along the necessary dimensions. This allows for efficient element-wise operations without the need for explicit reshaping.

Here's a simple example to illustrate broadcasting:




In [77]:
import numpy as np

# Create a 3x3 array
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Add a scalar to each element using broadcasting
result = A + 10

print("Original Array:")
print(A)

print("\nResult after Broadcasting:")
print(result)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result after Broadcasting:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
